### ISSUE TITLE
Plugin seems to be broken on windows 

### ISSUE THREAD

**Issue by peterlazzarino** [danielmahon/gatsby-remark-relative-images#11]
After tracking down an issue [here](https://github.com/gatsbyjs/gatsby/issues/5990#issuecomment-439666580 ) it seems that when using this plugin, the images are not query-able in a windows environment.

The bug is easily reproducible by cloning [this repo](https://github.com/cmmartti/gatsby-image-from-frontmatte) and attempting the query in the issue. I created a fork that only swaps out this plugin for another solution and the query works as expected on Windows. It has worked as expected on clones on mac and linux OSes. Here's [my fork](https://github.com/peterlazzarino/gatsby-image-from-frontmatter)

**Comment by Coder2012** [comment]
I've tested this PR on a couple of local projects using Windows 10. Working fine here.
