### ISSUE TITLE
Subfolders in assets result in overwrite images having the same names

### ISSUE THREAD

**Issue by tareefdev** [danielmahon/gatsby-remark-relative-images#17]
If there are subfolders inside `assets` which contain images have same names, like:
```
- assets
|_ sub-folder-1
|___ image1.png
|_ sub-folder-2
|___ image1.png
````
the following markdown will display `/assets/sub-folder-2/image1.png` for both of images:
````
[my-first-image](./assets/sub-folder-1/image1.png)
[my-second-image](./assets/sub-folder-2/image1.png)
````

**Comment by sarahbethfederman** [comment]
We are having this issue too, hope to see the fix make it in soon 👍
