### ISSUE TITLE
Relative URL conversion on unwanted frontmatter properies

### ISSUE THREAD

**Issue by megant** [danielmahon/gatsby-remark-relative-images#18]
OK, let me draw up the problem. When I call fmImagesToRelative(node) in the onCreateNode hook of gatsy-node.js, the node argument of the function contains all the node data. Let's say I create a page dynamically according to the markdow below:

`---

title: Title

image: /content/images/image_name.jpg

slug: /my/multilingual/slug`

When this markdown data passed to fmImagesToRelative function, in the inside at row 233. the image validation is like:

`if (!file.dir) return;`

It means everything that looks like image path is surely an image path. This approach is wrong, because in this way every path will be converted to relative path instead of only paths related to the plugin's settings, eg:

`plugins: [...
            {
              resolve: 'gatsby-remark-relative-images',
              options: {
                name: 'only-this-named-source',
              },
            },
...]`

You should handle this somehow, otherwise we've to face lot of unwanted issues at build process.

**Comment by danielmahon** [comment]
@megant I can see the issue here. I believe adding a "field" option to filter by would solve this. That way you could specify something like:
```js
{
  resolve: 'gatsby-remark-relative-images',
    options: {
     fmFields: ['image'],
    },
  },
}
```

**Comment by megant** [comment]
> @megant I can see the issue here. I believe adding a "field" option to filter by would solve this. That way you could specify something like:
> 
> ```js
> {
>   resolve: 'gatsby-remark-relative-images',
>     options: {
>      fmFields: ['image'],
>     },
>   },
> }
> ```

I tried something similar (I used exceptions instead of fmFields and in contained fields which don't have to be converted), but my problem was fmImagesToRelative runs before plugin options initialization.

**Comment by danielmahon** [comment]
Yea, I just found that out too. Sorry, I haven't used this much since I
wrote it :wink:. I will take a look at maybe passing a "filter" method
option to the function which you could use to determine which fields were
converted.

**Comment by devolasvegas** [comment]
@danielmahon Has there been any movement on this?

**Comment by angelod1as** [comment]
@danielmahon I'm having a similar issue. Having a filter would solve it.

**Comment by maciekgrzybek** [comment]
I could give it a go if it's still needed?

**Comment by danielmahon** [comment]
add options in fb63dd3
