### ISSUE TITLE
Use ^ versions for npm dependencies

### ISSUE THREAD

**Issue by igorakkerman** [danielmahon/gatsby-remark-relative-images#19]
Could you please change the dependency versions to be less strict to be future-proof, for instance:
```
"lodash": "^4.17.11",
```

The current lodash version produces an _npm audit_ issue:

>                                   Manual Review                                  
>              Some vulnerabilities require your attention to resolve             
>                                                                                 
>           Visit https://go.npm.me/audit-guide for additional guidance           
>                                                                                 
>                                                                                 
>   High            Prototype Pollution                                           
>                                                                                 
>   Package         lodash                                                        
>                                                                                 
>   Patched in      >=4.17.12                                                     
>                                                                                 
>   Dependency of   gatsby-remark-relative-images                                 
>                                                                                 
>   Path            gatsby-remark-relative-images > lodash                        
>                                                                                 
>   More info       https://npmjs.com/advisories/1065

**Comment by danielmahon** [comment]
Fixed in a271827
