### ISSUE TITLE
GIF image

### ISSUE THREAD

**Issue by eur2** [danielmahon/gatsby-remark-relative-images#23]
Hello, I'm using the plugin gatsby-remark-relative-images. Everything is working well. All the image (jpg) are well converted to relative path. Except when I have a GIF image instead of JPG into markdown content. Then the relative path doesn't work. Has anyone encountered this issue?

**Comment by maximeduhamel** [comment]
Hi, in another similar issue you can see an answer from Kyle  Mathews. I hope you'll find your answer there 😊

https://github.com/gatsbyjs/gatsby/issues/7317#issuecomment-412984851

**Comment by grdpr** [comment]
Thanks for the link! 
I tried it but that didn't work. I have this weird double relative path:
<img src="../../static/assets/a.gif" alt="" title="">

**Comment by smashercosmo** [comment]
Having the same problem. It should be possible to specify file extensions to be handled by the plugin.

**Comment by eur2** [comment]
@smashercosmo To make it working in gatsby, I'm using the publicUrl and a classic <img> tag.
