### ISSUE TITLE
Plugin stopped working when upgraded to gatsby 2.18.1

### ISSUE THREAD

**Issue by rjyo** [danielmahon/gatsby-remark-relative-images#26]
After upgrading gatsby to 2.18.1, I go the following error:

```
Field "featuredImage" must not have a selection since type "String" has no subfields
```

`featuredImage` is a field used in frontmatter with an absolute path. So I guess there must be something wrong with `fmImagesToRelative`.

When switch back to 2.17, the error will disappear.

**Comment by rjyo** [comment]
Seems it's gatsby's problem

**Comment by martondob** [comment]
Thanks @rjyo!
This seems to have fixed our nightmare issue we've been having for a week now!

**Comment by crgeee** [comment]
@rjyo  sigh...been fighting this is there an issue in gatsby you're referring to?
