### ISSUE TITLE
After migrate to 0.3.0, images doesn't work

### ISSUE THREAD

**Issue by felipefialho** [danielmahon/gatsby-remark-relative-images#31]
Hi,

In last week I've updated the dependency for 0.2.3 to 0.3.0 and images didn't work more.

I can't understand what is the cause of problem, but I think that gatsby-remark-relative-images doesn't resolve the paths anymore. 

For example (in prod), in 0.3.0: 

```
<img src="assets/2019-11-27-github-explore.png" alt="Github Explore">
```

In 0.2.3 working well.

**Comment by danielmahon** [comment]
@felipefialho I am looking into this today and testing with latest https://github.com/netlify-templates/gatsby-starter-netlify-cms starter

**Comment by danielmahon** [comment]
@felipefialho do you have your assets folder defined in gatsby-config.js? see my comment in #29 also
```
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        path: `${__dirname}/src/assets`,
        name: 'assets',
      },
    },
```

with the `src/assets` folder defined in `gatsby-config.js` the following works

**src/pages/blog/blog-post-1.md**
```
frontmatter
---
![coffee](../../assets/coffee.png)
<img src="../../assets/coffee.png" alt="Coffee" />
```

**Comment by felipefialho** [comment]
@danielmahon Yes, I have.

You can check [my source here](https://github.com/felipefialho/felipefialho.com/blob/master/gatsby-config.js), 😄

**Comment by DirtySoc** [comment]
I am also seeing an odd relative image resolving issue with 0.3.0. Going back to 0.2.2 makes it work again.

This works with both 0.2.2 and 0.3.0.
![image](https://user-images.githubusercontent.com/33207400/79400110-3cf62980-7f53-11ea-9ddb-be124545f45e.png)

This works with 0.2.2 and does NOT work with 0.3.0:
![image](https://user-images.githubusercontent.com/33207400/79400152-631bc980-7f53-11ea-9b8f-1262346e0d1d.png)

If you think this should be a separate issue. Please let me know.

**Comment by cwkosman** [comment]
I also have an independent case where downgrading from 0.3.0 to 0.2.3 is the solution and both all relevant config (gatsby-config.js and static.admin/config.yml) and the markdown files themselves remain unchanged.

On 0.3.0, images referenced within the body of markdown files are rendered out using the parent asset in a simple <img> tag.
![23-08-krq8q-qlymv](https://user-images.githubusercontent.com/23545041/82741503-6438d700-9d07-11ea-877c-b28bb19bca35.jpg)

On 0.2.3, images images from within the body of markdown files are rendered in a proper `gatsby-image`-like wrapper.
![23-03-wf2n1-blfli](https://user-images.githubusercontent.com/23545041/82741446-b6c5c380-9d06-11ea-9051-b37edc216b3f.jpg)

**Comment by Samic8** [comment]
Having this same issue when using 0.3.0

**Comment by felipefialho** [comment]
For now it works again. I've been using `"gatsby-remark-images": "^3.3.8"`. 

@Samic8 You can [check here](https://github.com/felipefialho/felipefialho.com/blob/master/package.json).
