### ISSUE TITLE
Document required Netlify CMS configuration

### ISSUE THREAD

**Issue by axelboc** [danielmahon/gatsby-remark-relative-images#4]
If I'm not mistaken, the plugin assumes that the configured Netlify CMS `public_folder` is one level down from the `media_folder` - e.g.

```yaml
media_folder: "static/uploads"
public_folder: "/uploads"
```

I'm referring more specifically to line [129](https://github.com/danielmahon/gatsby-remark-relative-images/blob/master/src/index.js#L129):

```js
imagePath = path.join(file.dir, '..', value);
```

If that's the case, it might be worth mentioning it in the README.

**Comment by danielmahon** [comment]
@axelboc I think you're right, probably better to use `path.basename` rather than jumping up a level.

**Comment by axelboc** [comment]
Ah yeah, great solution!
