### ISSUE TITLE
Not able to change to relative path in markdown

### ISSUE THREAD

**Issue by mattdvhope** [danielmahon/gatsby-remark-relative-images#5]
I really appreciate your work on this plugin.  For some reason I can't get it to work on my Gatsby app.  In `index.md`, I have this frontmatter:
```javascript
      ---
      templateKey: home-page/index
      image1: /img/City-Picture.jpg
      ---
```

In `home-page/index.js`, I have this query:

    export const homePageQuery = graphql`
      query HomePage($id: String!) {
        markdownRemark(id: { eq: $id }) {
          frontmatter {
            welcome_description
            image1 {
              childImageSharp {
                sizes(maxWidth: 590) {
                  ...GatsbyImageSharpSizes
                }
              }
            }
          }
        }
     }

In `gatsby-config.js`, I have:
```javascript
module.exports = {
  siteMetadata: {
    title: 'Gatsby + Netlify CMS Starter',
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/pages`, // path to markdown files
        name: `pages`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/static/img`,
        name: `images`,
      },
    },
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          // gatsby-remark-relative-images must
          // go before gatsby-remark-images
          {
            resolve: `gatsby-remark-relative-images`,
          },
          {
            resolve: `gatsby-remark-images`,
            options: {
              // It's important to specify the maxWidth (in pixels) of
              // the content container as this plugin uses this as the
              // base for generating different widths of each image.
              maxWidth: 590,
            },
          },
        ],
      },
    },
    {
      resolve: `gatsby-plugin-netlify-cms`,
      options: {
        modulePath: `${__dirname}/src/cms/cms.js`,
      },
    },
    `gatsby-plugin-meta-redirect`, 
    `gatsby-plugin-netlify`, // make sure to keep it last in the array
  ],
}
```

In `config.yml` I have:
```javascript
    media_folder: static/img
    public_folder: /img
```
In [325](https://github.com/netlify/netlify-cms/issues/325) you had mentioned that:

"So, given a node like `/src/pages/blog/my-first-post.md`, with an image src of `/uploads/fat-racoon.jpg`, and the referenced image in `/static/uploads` it changes the node.url to `.../.../../static/uploads/fat-racoon.jpg`. Which lets gatsby-remark-images resolve it correctly when it does `path.join(node.parent.dir, node.url)`."

For some reason when I run it in development or build mode, `image1` remains as `/img/City-Talk-Class.jpg` and does not transform into `../../static/img/City-Talk-Class.jpg` as I'd prefer.

I keep getting this error in my terminal:
```javascript
GraphQL Error Field "image1" must not have a selection since type "String" has no subfields.
     2 |   query HomePage($id: String!) {
     3 |     markdownRemark(id: { eq: $id }) {
     4 |       frontmatter {
     5 |         welcome_description
     6 |         image1 {
        |                ^
     7 |           childImageSharp {
     8 |             sizes(maxWidth: 590) {
     9 |               ...GatsbyImageSharpSizes
    10 |             }
    11 |           }
    12 |         }
    13 |       }
  14 |     }
```

Can you tell if I am implementing your plugin incorrectly?  Thank you so much!

**Comment by peterlazzarino** [comment]
I am having the same issue with the same set up using gatsby + netlify CMS

**Comment by joshuarule** [comment]
@mattdvhope @peterlazzarino are you on the latest? 0.1.2?

**Comment by ClintH** [comment]
I have a similar setup. Works fine on my local machine when doing a gatsby 'build' or 'develop', but not when the repo is deployed to Netlify.

**Comment by danielmahon** [comment]
@mattdvhope will try to check this out later today

**Comment by axelboc** [comment]
Seems like in some places you use `slash` to convert Windows backslashes to forward slashes, and this conflicts with `path.normalize`, which now does the opposite. Working on a PR now.

**Comment by pburtchaell** [comment]
In the meantime, if anyone is stuck on this and needs a quick solution, here's what I did. I just made a `remarkImagesToRelative` function and [manually joined the paths](https://github.com/pburtchaell/pburtchaell.com/blob/0d0813404b915f365e10bdc6be34a043adb27b1e/gatsby/remarkImagesToRelative.js#L5-L13).

**Comment by pburtchaell** [comment]
@danielmahon, any updates on the fix for this? If there's anyway I can help contribute, let me know.

**Comment by peterlazzarino** [comment]
@pburtchaell with your change are you successfully able to transform and use frontmatter images with childImageSharp? I have been going in circles on this one for a while now.

**Comment by kennedyrose** [comment]
I wrote a [separate plugin](https://github.com/escaladesports/gatsby-plugin-netlify-cms-paths) that will read the Netlify CMS config and adjust your paths accordingly. So it's a little different than this plugin as it requires you to use Netlify CMS. But if you are it might be a good solution. It's only a day old so there might be quirks!
