### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by steverandy** [danielmahon/gatsby-remark-relative-images#6]
Got the above error when upgrading gatsby to v2.0.0-beta.2

```
- index.js:48 
    [gatsby-remark-relative-images]/index.js:48:7
  
  - index.js:94 
    [gatsby-remark-relative-images]/index.js:94:6
  
  - Array.map
  
  - index.js:42 module.exports
    [gatsby-remark-relative-images]/index.js:42:22
```

**Comment by danielmahon** [comment]
@steverandy haven't tested with 2.0, will look into it, thanks for the report

**Comment by Jinksi** [comment]
I'm getting the same error using gatsby@2.0.0-beta.29

**Comment by muhajirframe** [comment]
Does it works now?

**Comment by floydnoel** [comment]
I got the error to resolve by adding `require('babel-polyfill')` to the top of my `gatsby-config.js` file.
